### ISSUE TITLE
issues with installing JAM

### ISSUE THREAD

**Issue by Bela1229** [johnmcculloch/JAMS_BW#1]
Hello,
Thanks for putting together a tutorial--I am having some difficulties with installing to my biowulf workplace.
 git clone https://github.com/johnmcculloch/JAMS_BW.git
Cloning into 'JAMS_BW'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 599 (delta 8), reused 13 (delta 5), pack-reused 579
Receiving objects: 100% (599/599), 5.33 MiB | 39.87 MiB/s, done.
Resolving deltas: 100% (323/323), done.
[xxx@cn3095 bin]$ cd JAMS_BW/
[xxx@cn3095 JAMS_BW]$ ./JAMSinstaller_BW --install
/usr/bin/env: Rscript: No such file or directory
I would appreciate your help!
@johnmcculloch

**Comment by johnmcculloch** [comment]
Hello,
Thanks for your interest in JAMS. The error message you are getting means
you don't have linuxbrew R on your Biowulf account. You can install it with:
brew install R gcc@8 libxml2

Then try running the Jams installer again:
./JAMSinstallerBW --install

**Comment by Bela1229** [comment]
Thank you for your quick response!
Actually I do have linuxbrew R on my account:
JAMS_BW]$ brew reinstall gcc@8 R
==> Reinstalling gcc@8
....
Then I ran
[xxx@cn3109 JAMS_BW]$ echo "/home/huangg3/bin/JAMS_BW/JAMSinstaller_BW --install" > installJAMS.swarm
[xxx@cn3109 JAMS_BW]$ swarm -g 32 -t 8 --time 6:00:00 --partition=norm --module R -f installJAMS.swarm
33955168
[xxx@cn3109 JAMS_BW]$ JAMSalpha -d /data/Microbiome/JAMSdb/db -a GCA_000969225.1 -H none -A isolate -n -p FCFHV36
bash: JAMSalpha: command not found
Same problem here.
@johnmcculloch

**Comment by johnmcculloch** [comment]
It looks like jams was not installed. What result did you get for the swarm
file you launched? The one under job ID 33955168 ?

**Comment by Bela1229** [comment]
You mean this step?
swarm -g 32 -t 8 --time 6:00:00 --partition=norm --module R -f installJAMS.swarm
It did not give me any results.
I would appreciate your help!
@johnmcculloch

**Comment by johnmcculloch** [comment]
You can see the results in the swarm output files. Like swarm_[jobid].o

**Comment by Bela1229** [comment]
Thanks!
My swarm_jobid_0.o and swarm_jobid_0.e all have nothing in it.
But I think I have all dependencies installed correctly.
@johnmcculloch
